name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar uv
        run: |
          pip install uv

          
      - name: Criar ambiente virtual com uv
        run: |
          uv venv .venv
          source .venv/bin/activate

      - name: Instalar dependências com uv
        run: |
          uv pip install .[dev]

      - name: Instalar taskipy
        run: |
          uv pip install taskipy

      - name: Rodar testes com taskipy
        run: |
          task test